version: '3.8'
services:
  db:
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: persona_grimoire_db
    ports:
      # <Port exposed> : < Postgres Port running inside container>
      - '5432:5432'
      # Where our data will be persisted
    volumes:
      - db:/var/lib/postgresql/data
# Names our volume
volumes:
  db:
    driver: local