// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Agility An integer that represents the Persona's Agility stat.
type Agility = int

// ArcanaID A universally unique identifier for identifying one of the 22 Major Arcana.
type ArcanaID = openapi_types.UUID

// ArcanaName The name of the Major Arcana.
type ArcanaName = string

// ArcanaNumber A number from 0 - 21 representing one of the 22 Major Arcana from tarot cards.
type ArcanaNumber = int

// ArcanaNumeral A Roman numeral representation of the Arcana Number. The exeception is the Fool Arcana which does not have an associated numeral. It is represented with "0".
type ArcanaNumeral = string

// CreatedAt Represents when the object was added to the database.
type CreatedAt time.Time

// Endurance An integer that represents the Persona's Endurance stat.
type Endurance = int

// ErrorBaseResponse defines model for ErrorBaseResponse.
type ErrorBaseResponse struct {
	Code    int    `json:"Code"`
	Data    string `json:"Data"`
	Error   bool   `json:"Error"`
	Message string `json:"Message"`
	Ping    bool   `json:"Ping"`
}

// IsDLC Represents if the Persona is only available via Downloadable Content.
type IsDLC = bool

// IsTreasureDemon Represents if the Persona is a treasure demon. Unique field to Persona 5 and Persona 5 Royal.
type IsTreasureDemon = bool

// Level The level of the Persona when first encountered; usually during fusion. The main character must be at least this level in order to fuse this Persona.
type Level = int

// Luck An integer that represents the Persona's Luck stat.
type Luck = int

// Magic An integer that represents the Persona's Magic stat.
type Magic = int

// P5Arcana defines model for P5Arcana.
type P5Arcana struct {
	// ArcanaID A universally unique identifier for identifying one of the 22 Major Arcana.
	ArcanaID ArcanaID `gorm:"type:uuid;primaryKey" json:"ArcanaID"`

	// ArcanaName The name of the Major Arcana.
	ArcanaName ArcanaName `json:"ArcanaName"`

	// ArcanaNumber A number from 0 - 21 representing one of the 22 Major Arcana from tarot cards.
	ArcanaNumber ArcanaNumber `json:"ArcanaNumber" validate:"minimum=0,maximum=21"`

	// ArcanaNumeral A Roman numeral representation of the Arcana Number. The exeception is the Fool Arcana which does not have an associated numeral. It is represented with "0".
	ArcanaNumeral ArcanaNumeral `json:"ArcanaNumeral"`
}

// P5ArcanaResponse defines model for P5ArcanaResponse.
type P5ArcanaResponse struct {
	// ArcanaName The name of the Major Arcana.
	ArcanaName ArcanaName `json:"ArcanaName"`

	// ArcanaNumber A number from 0 - 21 representing one of the 22 Major Arcana from tarot cards.
	ArcanaNumber ArcanaNumber `json:"ArcanaNumber" validate:"minimum=0,maximum=21"`

	// ArcanaNumeral A Roman numeral representation of the Arcana Number. The exeception is the Fool Arcana which does not have an associated numeral. It is represented with "0".
	ArcanaNumeral ArcanaNumeral `json:"ArcanaNumeral"`
}

// P5Persona defines model for P5Persona.
type P5Persona struct {
	// Arcana A universally unique identifier for identifying one of the 22 Major Arcana.
	Arcana ArcanaID `gorm:"type:uuid;primaryKey" json:"Arcana"`

	// CreatedAt Represents when the object was added to the database.
	CreatedAt CreatedAt `json:"-"`

	// IsDLC Represents if the Persona is only available via Downloadable Content.
	IsDLC *IsDLC `json:"IsDLC,omitempty"`

	// IsTreasureDemon Represents if the Persona is a treasure demon. Unique field to Persona 5 and Persona 5 Royal.
	IsTreasureDemon *IsTreasureDemon `json:"IsTreasureDemon,omitempty"`

	// Level The level of the Persona when first encountered; usually during fusion. The main character must be at least this level in order to fuse this Persona.
	Level Level `json:"Level" validate:"minimum=1,maximum=99"`

	// P5PersonaID A universally unique identifier for identifying a Persona from Persona 5.
	P5PersonaID *P5PersonaID `gorm:"type:uuid;primaryKey" json:"P5PersonaID,omitempty"`

	// PersonaName The name of the Persona.
	PersonaName *PersonaName `json:"PersonaName,omitempty" validate:"minimum=1,maximum=24"`

	// Skill A universally unique identifier for identifying a skill that a Persona 5 Persona can learn.
	Skill *P5SkillID `gorm:"type:uuid;primaryKey" json:"Skill,omitempty"`

	// UpdatedAt Represents the last time when the object was updated in the database.
	UpdatedAt UpdatedAt `json:"-"`
}

// P5PersonaID A universally unique identifier for identifying a Persona from Persona 5.
type P5PersonaID = openapi_types.UUID

// P5PersonaSkill defines model for P5PersonaSkill.
type P5PersonaSkill struct {
	// CreatedAt Represents when the object was added to the database.
	CreatedAt *CreatedAt `json:"-"`

	// SkillCost The cost to use the skill.
	SkillCost *SkillCost `json:"SkillCost,omitempty"`

	// SkillEffect The in-game description of what the skill does when used by the player.
	SkillEffect *SkillEffect `json:"SkillEffect,omitempty"`

	// SkillID A universally unique identifier for identifying a skill that a Persona 5 Persona can learn.
	SkillID *P5SkillID `gorm:"type:uuid;primaryKey" json:"SkillID,omitempty"`

	// SkillName The in-game name for the skill.
	SkillName *SkillName `json:"SkillName,omitempty"`

	// UpdatedAt Represents the last time when the object was updated in the database.
	UpdatedAt *UpdatedAt `json:"-"`
}

// P5PersonaStats defines model for P5PersonaStats.
type P5PersonaStats struct {
	// Agility An integer that represents the Persona's Agility stat.
	Agility Agility `json:"Agility" validate:"minimum=1,maximum=99"`

	// Endurance An integer that represents the Persona's Endurance stat.
	Endurance Endurance `json:"Endurance" validate:"minimum=1,maximum=99"`

	// Luck An integer that represents the Persona's Luck stat.
	Luck Luck `json:"Luck" validate:"minimum=1,maximum=99"`

	// Magic An integer that represents the Persona's Magic stat.
	Magic Magic `json:"Magic" validate:"minimum=1,maximum=99"`

	// StatsID A universally unique identifier for identifying a Persona 5 Persona's stats.
	StatsID openapi_types.UUID `gorm:"type:uuid;primaryKey" json:"StatsID"`

	// Strength An integer that represents the Persona's Strength stat.
	Strength Strength `json:"Strength" validate:"minimum=1,maximum=99"`
}

// P5SkillID A universally unique identifier for identifying a skill that a Persona 5 Persona can learn.
type P5SkillID = openapi_types.UUID

// PersonaName The name of the Persona.
type PersonaName = string

// SkillCost The cost to use the skill.
type SkillCost = string

// SkillEffect The in-game description of what the skill does when used by the player.
type SkillEffect = string

// SkillName The in-game name for the skill.
type SkillName = string

// Strength An integer that represents the Persona's Strength stat.
type Strength = int

// UpdatedAt Represents the last time when the object was updated in the database.
type UpdatedAt time.Time

// BadRequest defines model for BadRequest.
type BadRequest = ErrorBaseResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorBaseResponse

// GetAllPersona5Arcanas defines model for GetAllPersona5Arcanas.
type GetAllPersona5Arcanas = []P5ArcanaResponse

// GetArcana defines model for GetArcana.
type GetArcana = P5ArcanaResponse

// MissingSubject defines model for MissingSubject.
type MissingSubject = ErrorBaseResponse

// NoContent defines model for NoContent.
type NoContent = map[string]interface{}

// NotFound defines model for NotFound.
type NotFound = ErrorBaseResponse

// ServerError defines model for ServerError.
type ServerError = ErrorBaseResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorBaseResponse

// GetAllPersona5ArcanasParams defines parameters for GetAllPersona5Arcanas.
type GetAllPersona5ArcanasParams struct {
	// Limit The maximum number of records to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The number of records to skip.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAllPersona5Arcanas request
	GetAllPersona5Arcanas(ctx context.Context, params *GetAllPersona5ArcanasParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPersona5ArcanaByUUID request
	GetPersona5ArcanaByUUID(ctx context.Context, arcanaUUID ArcanaID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPersona5ArcanaByName request
	GetPersona5ArcanaByName(ctx context.Context, arcanaName ArcanaName, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAllPersona5Arcanas(ctx context.Context, params *GetAllPersona5ArcanasParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAllPersona5ArcanasRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPersona5ArcanaByUUID(ctx context.Context, arcanaUUID ArcanaID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPersona5ArcanaByUUIDRequest(c.Server, arcanaUUID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPersona5ArcanaByName(ctx context.Context, arcanaName ArcanaName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPersona5ArcanaByNameRequest(c.Server, arcanaName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAllPersona5ArcanasRequest generates requests for GetAllPersona5Arcanas
func NewGetAllPersona5ArcanasRequest(server string, params *GetAllPersona5ArcanasParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/grimoire/v1/p5/arcana/all")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.Limit != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.Offset != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPersona5ArcanaByUUIDRequest generates requests for GetPersona5ArcanaByUUID
func NewGetPersona5ArcanaByUUIDRequest(server string, arcanaUUID ArcanaID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "arcanaUUID", runtime.ParamLocationPath, arcanaUUID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/grimoire/v1/p5/arcana/id/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPersona5ArcanaByNameRequest generates requests for GetPersona5ArcanaByName
func NewGetPersona5ArcanaByNameRequest(server string, arcanaName ArcanaName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "arcanaName", runtime.ParamLocationPath, arcanaName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/grimoire/v1/p5/arcana/name/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAllPersona5Arcanas request
	GetAllPersona5ArcanasWithResponse(ctx context.Context, params *GetAllPersona5ArcanasParams, reqEditors ...RequestEditorFn) (*GetAllPersona5ArcanasResponse, error)

	// GetPersona5ArcanaByUUID request
	GetPersona5ArcanaByUUIDWithResponse(ctx context.Context, arcanaUUID ArcanaID, reqEditors ...RequestEditorFn) (*GetPersona5ArcanaByUUIDResponse, error)

	// GetPersona5ArcanaByName request
	GetPersona5ArcanaByNameWithResponse(ctx context.Context, arcanaName ArcanaName, reqEditors ...RequestEditorFn) (*GetPersona5ArcanaByNameResponse, error)
}

type GetAllPersona5ArcanasResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]P5ArcanaResponse
	JSON400      *ErrorBaseResponse
	JSON500      *ErrorBaseResponse
}

// Status returns HTTPResponse.Status
func (r GetAllPersona5ArcanasResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAllPersona5ArcanasResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPersona5ArcanaByUUIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *P5ArcanaResponse
	JSON404      *ErrorBaseResponse
	JSON500      *ErrorBaseResponse
}

// Status returns HTTPResponse.Status
func (r GetPersona5ArcanaByUUIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPersona5ArcanaByUUIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPersona5ArcanaByNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *P5ArcanaResponse
	JSON404      *ErrorBaseResponse
	JSON500      *ErrorBaseResponse
}

// Status returns HTTPResponse.Status
func (r GetPersona5ArcanaByNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPersona5ArcanaByNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAllPersona5ArcanasWithResponse request returning *GetAllPersona5ArcanasResponse
func (c *ClientWithResponses) GetAllPersona5ArcanasWithResponse(ctx context.Context, params *GetAllPersona5ArcanasParams, reqEditors ...RequestEditorFn) (*GetAllPersona5ArcanasResponse, error) {
	rsp, err := c.GetAllPersona5Arcanas(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAllPersona5ArcanasResponse(rsp)
}

// GetPersona5ArcanaByUUIDWithResponse request returning *GetPersona5ArcanaByUUIDResponse
func (c *ClientWithResponses) GetPersona5ArcanaByUUIDWithResponse(ctx context.Context, arcanaUUID ArcanaID, reqEditors ...RequestEditorFn) (*GetPersona5ArcanaByUUIDResponse, error) {
	rsp, err := c.GetPersona5ArcanaByUUID(ctx, arcanaUUID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPersona5ArcanaByUUIDResponse(rsp)
}

// GetPersona5ArcanaByNameWithResponse request returning *GetPersona5ArcanaByNameResponse
func (c *ClientWithResponses) GetPersona5ArcanaByNameWithResponse(ctx context.Context, arcanaName ArcanaName, reqEditors ...RequestEditorFn) (*GetPersona5ArcanaByNameResponse, error) {
	rsp, err := c.GetPersona5ArcanaByName(ctx, arcanaName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPersona5ArcanaByNameResponse(rsp)
}

// ParseGetAllPersona5ArcanasResponse parses an HTTP response from a GetAllPersona5ArcanasWithResponse call
func ParseGetAllPersona5ArcanasResponse(rsp *http.Response) (*GetAllPersona5ArcanasResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAllPersona5ArcanasResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []P5ArcanaResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorBaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorBaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetPersona5ArcanaByUUIDResponse parses an HTTP response from a GetPersona5ArcanaByUUIDWithResponse call
func ParseGetPersona5ArcanaByUUIDResponse(rsp *http.Response) (*GetPersona5ArcanaByUUIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPersona5ArcanaByUUIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest P5ArcanaResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorBaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorBaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetPersona5ArcanaByNameResponse parses an HTTP response from a GetPersona5ArcanaByNameWithResponse call
func ParseGetPersona5ArcanaByNameResponse(rsp *http.Response) (*GetPersona5ArcanaByNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPersona5ArcanaByNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest P5ArcanaResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorBaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorBaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /grimoire/v1/p5/arcana/all)
	GetAllPersona5Arcanas(ctx echo.Context, params GetAllPersona5ArcanasParams) error

	// (GET /grimoire/v1/p5/arcana/id/{arcanaUUID})
	GetPersona5ArcanaByUUID(ctx echo.Context, arcanaUUID ArcanaID) error

	// (GET /grimoire/v1/p5/arcana/name/{arcanaName})
	GetPersona5ArcanaByName(ctx echo.Context, arcanaName ArcanaName) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAllPersona5Arcanas converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllPersona5Arcanas(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllPersona5ArcanasParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetAllPersona5Arcanas(ctx, params)
	return err
}

// GetPersona5ArcanaByUUID converts echo context to params.
func (w *ServerInterfaceWrapper) GetPersona5ArcanaByUUID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "arcanaUUID" -------------
	var arcanaUUID ArcanaID

	err = runtime.BindStyledParameterWithLocation("simple", false, "arcanaUUID", runtime.ParamLocationPath, ctx.Param("arcanaUUID"), &arcanaUUID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter arcanaUUID: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPersona5ArcanaByUUID(ctx, arcanaUUID)
	return err
}

// GetPersona5ArcanaByName converts echo context to params.
func (w *ServerInterfaceWrapper) GetPersona5ArcanaByName(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "arcanaName" -------------
	var arcanaName ArcanaName

	err = runtime.BindStyledParameterWithLocation("simple", false, "arcanaName", runtime.ParamLocationPath, ctx.Param("arcanaName"), &arcanaName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter arcanaName: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPersona5ArcanaByName(ctx, arcanaName)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/grimoire/v1/p5/arcana/all", wrapper.GetAllPersona5Arcanas)
	router.GET(baseURL+"/grimoire/v1/p5/arcana/id/:arcanaUUID", wrapper.GetPersona5ArcanaByUUID)
	router.GET(baseURL+"/grimoire/v1/p5/arcana/name/:arcanaName", wrapper.GetPersona5ArcanaByName)

}

type BadRequestJSONResponse ErrorBaseResponse

type ForbiddenJSONResponse ErrorBaseResponse

type GetAllPersona5ArcanasJSONResponse []P5ArcanaResponse

type GetArcanaJSONResponse P5ArcanaResponse

type MissingSubjectJSONResponse ErrorBaseResponse

type NoContentJSONResponse map[string]interface{}

type NotFoundJSONResponse ErrorBaseResponse

type ServerErrorJSONResponse ErrorBaseResponse

type UnauthorizedJSONResponse ErrorBaseResponse

type GetAllPersona5ArcanasRequestObject struct {
	Params GetAllPersona5ArcanasParams
}

type GetAllPersona5ArcanasResponseObject interface {
	VisitGetAllPersona5ArcanasResponse(w http.ResponseWriter) error
}

type GetAllPersona5Arcanas200JSONResponse = GetAllPersona5ArcanasJSONResponse

func (response GetAllPersona5Arcanas200JSONResponse) VisitGetAllPersona5ArcanasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllPersona5Arcanas400JSONResponse = BadRequestJSONResponse

func (response GetAllPersona5Arcanas400JSONResponse) VisitGetAllPersona5ArcanasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAllPersona5Arcanas500JSONResponse = ServerErrorJSONResponse

func (response GetAllPersona5Arcanas500JSONResponse) VisitGetAllPersona5ArcanasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPersona5ArcanaByUUIDRequestObject struct {
	ArcanaUUID ArcanaID `json:"arcanaUUID"`
}

type GetPersona5ArcanaByUUIDResponseObject interface {
	VisitGetPersona5ArcanaByUUIDResponse(w http.ResponseWriter) error
}

type GetPersona5ArcanaByUUID200JSONResponse = GetArcanaJSONResponse

func (response GetPersona5ArcanaByUUID200JSONResponse) VisitGetPersona5ArcanaByUUIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPersona5ArcanaByUUID404JSONResponse = NotFoundJSONResponse

func (response GetPersona5ArcanaByUUID404JSONResponse) VisitGetPersona5ArcanaByUUIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPersona5ArcanaByUUID500JSONResponse = ServerErrorJSONResponse

func (response GetPersona5ArcanaByUUID500JSONResponse) VisitGetPersona5ArcanaByUUIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPersona5ArcanaByNameRequestObject struct {
	ArcanaName ArcanaName `json:"arcanaName"`
}

type GetPersona5ArcanaByNameResponseObject interface {
	VisitGetPersona5ArcanaByNameResponse(w http.ResponseWriter) error
}

type GetPersona5ArcanaByName200JSONResponse = GetArcanaJSONResponse

func (response GetPersona5ArcanaByName200JSONResponse) VisitGetPersona5ArcanaByNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPersona5ArcanaByName404JSONResponse = NotFoundJSONResponse

func (response GetPersona5ArcanaByName404JSONResponse) VisitGetPersona5ArcanaByNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPersona5ArcanaByName500JSONResponse = ServerErrorJSONResponse

func (response GetPersona5ArcanaByName500JSONResponse) VisitGetPersona5ArcanaByNameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /grimoire/v1/p5/arcana/all)
	GetAllPersona5Arcanas(ctx context.Context, request GetAllPersona5ArcanasRequestObject) (GetAllPersona5ArcanasResponseObject, error)

	// (GET /grimoire/v1/p5/arcana/id/{arcanaUUID})
	GetPersona5ArcanaByUUID(ctx context.Context, request GetPersona5ArcanaByUUIDRequestObject) (GetPersona5ArcanaByUUIDResponseObject, error)

	// (GET /grimoire/v1/p5/arcana/name/{arcanaName})
	GetPersona5ArcanaByName(ctx context.Context, request GetPersona5ArcanaByNameRequestObject) (GetPersona5ArcanaByNameResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetAllPersona5Arcanas operation middleware
func (sh *strictHandler) GetAllPersona5Arcanas(ctx echo.Context, params GetAllPersona5ArcanasParams) error {
	var request GetAllPersona5ArcanasRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllPersona5Arcanas(ctx.Request().Context(), request.(GetAllPersona5ArcanasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllPersona5Arcanas")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAllPersona5ArcanasResponseObject); ok {
		return validResponse.VisitGetAllPersona5ArcanasResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetPersona5ArcanaByUUID operation middleware
func (sh *strictHandler) GetPersona5ArcanaByUUID(ctx echo.Context, arcanaUUID ArcanaID) error {
	var request GetPersona5ArcanaByUUIDRequestObject

	request.ArcanaUUID = arcanaUUID

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPersona5ArcanaByUUID(ctx.Request().Context(), request.(GetPersona5ArcanaByUUIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPersona5ArcanaByUUID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPersona5ArcanaByUUIDResponseObject); ok {
		return validResponse.VisitGetPersona5ArcanaByUUIDResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetPersona5ArcanaByName operation middleware
func (sh *strictHandler) GetPersona5ArcanaByName(ctx echo.Context, arcanaName ArcanaName) error {
	var request GetPersona5ArcanaByNameRequestObject

	request.ArcanaName = arcanaName

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPersona5ArcanaByName(ctx.Request().Context(), request.(GetPersona5ArcanaByNameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPersona5ArcanaByName")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPersona5ArcanaByNameResponseObject); ok {
		return validResponse.VisitGetPersona5ArcanaByNameResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xaW2/bOhL+KwR3gX2R7SRNgFMX5yGXtghOe1CkzVObh7E0stlKpEpSSb2B//tiSEqi",
	"bfnSpFmk5ymWNMP55sK5kLnnqSorJVFaw8f3XKOplDToHs4gu8LvNRpLT6mSFqX7CVVViBSsUHL01ShJ",
	"70w6wxLo17815nzM/zXqlh75r2b0Wmulz8DgVRDEF4tFwjM0qRYVLcjH/NNMGIZEyfyHCRp2N0PJ7AyZ",
	"9pBYquoiY1JZNkGW10UuigKzoWNWuUXJZlBVKA2bYAq1QaZyBqwUxgg5bZepQEOJFvWQLxL+RumJyDKU",
	"z0nj2qBmmULjtJ3BLbIKtVNESWYVgzRFYxgwjUbVOkWny1u0p0XxAbVREk5OdQoSzE/pJSyWZpeCH8LS",
	"nX4Jt/MK+ZiD1jDv0/cKba0lA8kcCXnGL8LU5Cum1rQKuLe/zBnrWLdhW4LkEL33wfOxdq+eU4ykhUBp",
	"mTBtgMd7xdSdDn+r8w7z3vCDR70t+uF14u7AMFO7oMzrgk1qy7SzKtKGZRlYCFDsG1XL7LkYEthU3KJs",
	"txFLQTYJhnA60B9R36J2kp4LbqNKtDNy+gSykPYwY0oyVWuGAfi1hNrOlBb/xezZpTeJmBnKZRNkHUw2",
	"wVxpDAnOR7UwcZpbJAGoy1OnU1EIO6efywhOJRPS4hQ1szOgcKw0GtLEQQhJ8j+GhRWYsWCHvM1kgZkn",
	"/MdAQSUGqcpwinKAP6yGgYWpk38LhcjAEkcppCjr8s/DpIQf7tfLlw6uzyqXFz0gWS3FLWoDRTGn399r",
	"ZCJDaUUuULNc6eZxTrZQ0tU0UuDoiL2Hr0qHnEXIc6VLsHzM61pkPOEVWIua5HyGQX46eHMweHlz/8di",
	"ED8eLwbH8fOLxeDzHy9hcnp2s/o6ejw8WnSmMlYLOd1lqanSJR87njEBfFVpUYKe/4XzyEp/Q4nrdqJU",
	"I6FslV/VfBXIslfeoZza2Z8vyC/h9+HBdriyLooOU11OUPd5T7ovLNeqZAdswI4Ouzjb7i/PY0Ery1LQ",
	"mfkloXfQht7RYWzUukQNRZ8GV6oESXoQQQfeJYYGekDszTBk5Az8gSm6VagAEdEbpYqG8m4m0tlK/0KV",
	"3xiVCrBUE7zAIbt0FayVixm7E3bGvvCDL3y3Z1f228leTj3XSBhO7bo9rrok0SYrXwBdhYMsw4xSFr2n",
	"mjYBg8PejTBVg/DSihKHn0SJu/zp0zAfOMe9llmtQab4iMzWrvGEuW29GozveaVVhdoKP1ScqwyjhqIR",
	"vkj4Bdi41Qjma1aNvkyUKhCka8jQGJhiL9sH+tvDtUg4NSpCUxn87MUmHle3YCM1LHOTrHZACb80F+/O",
	"t0aNyGMfUGgrWcwZ3IIoYFIguxXALtSdLBRk7kVozSLvRMpemk8awdQaL7D0RfonRAOzgZtlxD5k177C",
	"5AILF8cN8QkDmUVPV2oORT+kd3iLRX+GLuhTkzSaxdw+yoU2lqFMVS0tasxesdrUruhlNXmP5TWNNj65",
	"lCAkS2egIbWoWVkb15CBZQWCsb4j8MKEZEpntBMULYH+W5D9NBH/rk6/PWJTEvsT7sf3MBXpI+A5/ifE",
	"18xj62ki7pK29Z8t3VrPsJvLUfbU9T04PW1fSd2L2RGvJqJWlRVES4qtSuxLTGtT7gbr/uaWerh5QoBv",
	"ssvPxNxS+7CNqSOMS8c2Dk/Un/e38y2Tx2l6G58nig20e/vFpMTpH/YJrJiUpupvoih2S3NkXtZ1le1n",
	"+Y5wNY467AkP4eON0IQRTzj5IOHLFo3dHgNZi7b9hiAaccVU/oXzcRNarzTmqFGmaMK7kC+XPPO48RHa",
	"quymj7be//7DY2umNqpWetAHbVq32LkyO7k6wobrdZ6H88KdfIG04dxnC0abwv3cZ/t1hA/fSo+MdQch",
	"DvRWjyUXWvBXEyuZujvp2ZqqA9nqDLX1SKsljPq7rYmTaOJuaxuxJyJXkWK/dh+fRK0bNW3m99/KH612",
	"ZzQ747mhW83xjZmjpRpPxTGRtBEVfP74XB4l66UoD4B8lEeb/LFRYGgp39D3hARLQdLEpOU/IL8vtxnb",
	"TwfXx7/9QGydX46OfXTGJWEdRqpoPlXMj6LoPbQOZL1KrC8l5GBKSkVfSME78na7tD9kczN2bTBjk7n7",
	"VhUwR71Z7mY7NlKdPSnidmgRbdYHTpzNEk84dC5Vu40HKASrcOcLosTe87/ar8OEfPITQIItZK7ccZaw",
	"Ba3T7Ou3WpRKaGSnHy55willeGUOhwfklEKkGIZA6RzNzz5eDF4MzguoDYGodcHHfGZtZcajkapQhtsV",
	"paejwG1GS0yLhBMdVIKP+Yvhgc8gMwd7NA2ARreHo+pkBK59HYFvxKbYY/a3aBkUzYGx6elHqfS7U+jL",
	"zNP33GwThnCXb/j4c188h0hoTupVzjSmSvubJ39FSdIE0X+vUVM1CEYrRCmoCKxdibYnmIukNxX1iTLf",
	"RLVJkMpzgzsk3STL/6lxdHCwqUC2dKN+qy0SfrwPd/TPIIuEn+zDEt+Uun7RBXYzvvMberchWkQ2uvc/",
	"r68vLxabI+f1J6p8FaYiF2lz4zCZM2HN9gLaG1XLxjmbk/B94oro3L+XyOgayjmXtkXn204lHncpVteY",
	"7Hnh2h0+PDwKwkBJnj/ezdHe0v8f/E52ajxPZemBnqdl9nJwmPp3OrhpKPZzcFj1MQ72o9lv7OLF4n8B",
	"AAD//4HoSm1cJgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
