openapi: "3.0"
info:
  title: Persona Grimoire API
  version: "1.0"
license:
  name: BSD-3-Clause
  url: https://opensource.org/licenses/BSD-3-Clause
paths:
  # Arcanas
  # GET
  /grimoire/v1/p5/arcana/id/{arcanaUUID}:
    get:
      operationId: getPersona5ArcanaByUUID
      tags:
        - Arcana
      description: GET a specific Arcana by its universally unique identifier.
      parameters:
        - name: arcanaUUID
          in: path
          description: The UUID of an Arcana.
          required: true
          schema:
            $ref: "#/components/schemas/ArcanaID"
      responses:
        200:
          $ref: "#/components/responses/GetArcanaByUUID"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/ServerError"
  /grimoire/v1/p5/arcana/name/{arcanaName}:
    get:
      operationId: getPersona5ArcanaByName
      tags:
        - Arcana
      description: GET a specific Arcana by its name.
      parameters:
        - name: arcanaName
          in: path
          description: The name of an Arcana.
          required: true
          schema:
            $ref: "#/components/schemas/ArcanaName"
      responses:
        200:
          $ref: "#/components/responses/GetArcanaByUUID"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/ServerError"
components:
  responses:
    # Arcana
    # GET Responses
    GetArcanaByUUID:
      description: Return an Arcana object.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/P5Arcana"
    NoContent:
      description: The request was successful but returned no data.
      content:
        application/json:
          schema:
            type: object
    BadRequest:
      description: This error describes when the request could not be fulfilled.This often happens because of a missing request parameter.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBaseResponse"
    Unauthorized:
      description: This error describes when the user needs to be authorized before accessing this resource.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBaseResponse"
    Forbidden:
      description: This error describes when the user does not have permission to access a resource.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBaseResponse"
    NotFound:
      description: This error describes when a given resource cannot be found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBaseResponse"
    ServerError:
      description: This error describes when something bad happened on our end.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBaseResponse"
    MissingSubject:
      description: This error describes when the client is missing the request subject.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBaseResponse"
  schemas:
    ErrorBaseResponse:
      description:
      type: object
      required:
        - Data
        - Code
        - Message
        - Error
        - Ping
      properties:
        Data:
          type: string
        Code:
          type: integer
        Message:
          type: string
        Error:
          type: boolean
        Ping:
          type: boolean

    ####################
    # Database Schemas #
    ####################
    P5Persona:
      x-oapi-codegen-extra-tags:
        gorm: "foreignKey:ArcanaID;references:Arcana"
      type: object
      required:
        - PersonaID
        - Name
        - Level
        - Arcana
        - DLC
        - TreasureDemon
        - CreatedAt
        - UpdatedAt
      properties:
        P5PersonaID:
          $ref: "#/components/schemas/P5PersonaID"
        PersonaName:
          $ref: "#/components/schemas/PersonaName"
        Level:
          $ref: "#/components/schemas/Level"
        Arcana:
          $ref: "#/components/schemas/ArcanaID"
        IsDLC:
          $ref: "#/components/schemas/IsDLC"
        IsTreasureDemon:
          $ref: "#/components/schemas/IsTreasureDemon"
        CreatedAt:
          $ref: "#/components/schemas/CreatedAt"
        UpdatedAt:
          $ref: "#/components/schemas/UpdatedAt"
        Skill:
          $ref: "#/components/schemas/P5SkillID"
    P5Arcana:
      type: object
      required:
        - ArcanaID
        - ArcanaNumber
        - ArcanaName
        - ArcanaNumeral
      properties:
        ArcanaID:
          $ref: "#/components/schemas/ArcanaID"
        ArcanaNumber:
          $ref: "#/components/schemas/ArcanaNumber"
        ArcanaName:
          $ref: "#/components/schemas/ArcanaName"
        ArcanaNumeral:
          $ref: "#/components/schemas/ArcanaNumeral"
    P5PersonaStats:
      x-oapi-codegen-extra-tags:
        gorm: "foreignKey:P5PersonaID;references:StatsID"
      type: object
      required:
        - StatsID
        - Strength
        - Magic
        - Endurance
        - Agility
        - Luck
      properties:
        StatsID:
          description: A universally unique identifier for identifying a Persona 5 Persona's stats.
          type: string
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
          x-oapi-codegen-extra-tags:
            gorm: "type:uuid;primaryKey"
        Strength:
          $ref: "#/components/schemas/Strength"
        Magic:
          $ref: "#/components/schemas/Magic"
        Endurance:
          $ref: "#/components/schemas/Endurance"
        Agility:
          $ref: "#/components/schemas/Agility"
        Luck:
          $ref: "#/components/schemas/Luck"
    P5PersonaSkill:
      x-oapi-codegen-extra-tags:
        gorm: "foreignKey:Skill;references:SkillID"
      type: object
      properties:
        SkillID:
          $ref: "#/components/schemas/P5SkillID"
        SkillName:
          $ref: "#/components/schemas/SkillName"
        SkillCost:
          $ref: "#/components/schemas/SkillCost"
        SkillEffect:
          $ref: "#/components/schemas/SkillEffect"
        CreatedAt:
          $ref: "#/components/schemas/CreatedAt"
        UpdatedAt:
          $ref: "#/components/schemas/UpdatedAt"
    ####################
    # Referenced Types #
    ####################
    # Generic Types
    CreatedAt:
      description: Represents when the object was added to the database.
      type: string
      x-go-type: time.Time
      x-oapi-codegen-extra-tags:
        json: "-"
    Level:
      description: The level of the Persona when first encountered; usually during fusion. The main character must be at least this level in order to fuse this Persona.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "min=1,max=99"
    UpdatedAt:
      description: Represents the last time when the object was updated in the database.
      type: string
      x-go-type: time.Time
      x-oapi-codegen-extra-tags:
        json: "-"
    # Arcanas
    ArcanaID:
      description: A universally unique identifier for identifying one of the 22 Major Arcana.
      type: string
      x-go-type: uuid.UUID
      x-go-type-import:
        path: github.com/google/uuid
      x-oapi-codegen-extra-tags:
        gorm: "type:uuid;primaryKey"
    ArcanaName:
      description: The name of the Major Arcana.
      type: string
      x-oapi-codegen-extra-tags:
      validate: "min=3,max=10"
    ArcanaNumber:
      description: A number from 0 - 21 representing one of the 22 Major Arcana from tarot cards.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "min=0,max=21"
    ArcanaNumeral:
      description: A Roman numeral representation of the Arcana Number. The exeception is the Fool Arcana which does not have an associated numeral. It is represented with "0".
      type: string
      x-oapi-codegen-extra-tags:
      validate: "min=1,max=3"
    # P5 Personas
    P5PersonaID:
      description: A universally unique identifier for identifying a Persona from Persona 5.
      type: string
      x-go-type: uuid.UUID
      x-go-type-import:
        path: github.com/google/uuid
      x-oapi-codegen-extra-tags:
        gorm: "type:uuid;primaryKey"
    IsDLC:
      description: Represents if the Persona is only available via Downloadable Content.
      type: boolean
    IsTreasureDemon:
      description: Represents if the Persona is a treasure demon. Unique field to Persona 5 and Persona 5 Royal.
      type: boolean
    PersonaName:
      description: The name of the Persona.
      type: string
      x-oapi-codegen-extra-tags:
        validate: "min=1,max=24"
    # P5 Skills
    P5SkillID:
      description: A universally unique identifier for identifying a skill that a Persona 5 Persona can learn.
      type: string
      x-go-type: uuid.UUID
      x-go-type-import:
        path: github.com/google/uuid
      x-oapi-codegen-extra-tags:
        gorm: "type:uuid;primaryKey"
    SkillName:
      description: The in-game name for the skill.
      type: string
    SkillCost:
      description: The cost to use the skill.
      type: string
    SkillEffect:
      description: The in-game description of what the skill does when used by the player.
      type: string
    # Stats
    Strength:
      description: An integer that represents the Persona's Strength stat.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "min=1,max=99"
    Magic:
      description: An integer that represents the Persona's Magic stat.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "min=1,max=99"
    Endurance:
      description: An integer that represents the Persona's Endurance stat.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "min=1,max=99"
    Agility:
      description: An integer that represents the Persona's Agility stat.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "min=1,max=99"
    Luck:
      description: An integer that represents the Persona's Luck stat.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "min=1,max=99"
