openapi: "3.0"
info:
  title: Persona Grimoire API
  version: "1.0"
license:
  name: BSD-3-Clause
  url: https://opensource.org/licenses/BSD-3-Clause
paths:
  # Arcanas
  # GET
  /grimoire/v1/p5/arcana/id/{arcanaUUID}:
    get:
      operationId: getPersona5ArcanaByUUID
      tags:
        - Arcana
      description: GET a specific Arcana by its universally unique identifier.
      parameters:
        - name: arcanaUUID
          in: path
          description: The UUID of an Arcana.
          required: true
          schema:
            $ref: "#/components/schemas/ArcanaID"
      responses:
        200:
          $ref: "#/components/responses/GetPersona5Arcana"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/ServerError"
  /grimoire/v1/p5/arcana/name/{arcanaName}:
    get:
      operationId: getPersona5ArcanaByName
      tags:
        - Arcana
      description: GET a specific Arcana by its name.
      parameters:
        - name: arcanaName
          in: path
          description: The name of an Arcana.
          required: true
          schema:
            $ref: "#/components/schemas/ArcanaName"
      responses:
        200:
          $ref: "#/components/responses/GetPersona5Arcana"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/ServerError"
  /grimoire/v1/p5/arcana/all:
    get:
      operationId: getAllPersona5Arcanas
      tags:
        - Arcana
      description: Get all Arcanas from Persona 5.
      parameters:
        - name: limit
          in: query
          description: The maximum number of records to return.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The number of records to skip.
          required: false
          schema:
            type: integer
      responses:
        200:
          $ref: "#/components/responses/GetAllPersona5Arcanas"
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/ServerError"
  # Personas
  # CREATE
  /grimoire/v1/p5/persona/create:
    post:
      operationId: createPersona5Persona
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/P5Persona"
components:
  responses:
    # Arcana
    # GET Responses
    GetPersona5Arcana:
      description: Return an Arcana object.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/P5ArcanaResponse"
    GetAllPersona5Arcanas:
      description: Return an array of Arcana objects.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/P5ArcanaResponse"
    NoContent:
      description: The request was successful but returned no data.
      content:
        application/json:
          schema:
            type: object
    BadRequest:
      description: This error describes when the request could not be fulfilled.This often happens because of a missing request parameter.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBaseResponse"
    Unauthorized:
      description: This error describes when the user needs to be authorized before accessing this resource.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBaseResponse"
    Forbidden:
      description: This error describes when the user does not have permission to access a resource.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBaseResponse"
    NotFound:
      description: This error describes when a given resource cannot be found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBaseResponse"
    ServerError:
      description: This error describes when something bad happened on our end.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBaseResponse"
    MissingSubject:
      description: This error describes when the client is missing the request subject.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBaseResponse"
  schemas:
    ErrorBaseResponse:
      description:
      type: object
      required:
        - Data
        - Code
        - Message
        - Error
        - Ping
      properties:
        Data:
          type: string
        Code:
          type: integer
        Message:
          type: string
        Error:
          type: boolean
        Ping:
          type: boolean

    ####################
    # Database Schemas #
    ####################
    P5Persona:
      type: object
      required:
        - P5PersonaID
        - Name
        - Level
        - ArcanaName
        - DLC
        - TreasureDemon
        - CreatedAt
        - UpdatedAt
      properties:
        P5PersonaID:
          $ref: "#/components/schemas/P5PersonaID"
        Name:
          x-oapi-codegen-extra-tags:
            gorm: "many2many:P5PersonaSkillJunction;"
          $ref: "#/components/schemas/PersonaName"
        Level:
          $ref: "#/components/schemas/Level"
        Arcana:
          x-oapi-codegen-extra-tags:
            gorm: "foreignKey:ArcanaName"
          $ref: "#/components/schemas/ArcanaName"
        IsDLC:
          $ref: "#/components/schemas/IsDLC"
        IsTreasureDemon:
          $ref: "#/components/schemas/IsTreasureDemon"
        CreatedAt:
          $ref: "#/components/schemas/CreatedAt"
        UpdatedAt:
          $ref: "#/components/schemas/UpdatedAt"
        Strength:
          $ref: "#/components/schemas/Strength"
        Magic:
          $ref: "#/components/schemas/Magic"
        Endurance:
          $ref: "#/components/schemas/Endurance"
        Agility:
          $ref: "#/components/schemas/Agility"
        Luck:
          $ref: "#/components/schemas/Luck"
    P5Arcana:
      type: object
      required:
        - ArcanaID
        - ArcanaNumber
        - ArcanaName
        - ArcanaNumeral
      properties:
        ArcanaID:
          $ref: "#/components/schemas/ArcanaID"
        ArcanaNumber:
          $ref: "#/components/schemas/ArcanaNumber"
        ArcanaName:
          $ref: "#/components/schemas/ArcanaName"
        ArcanaNumeral:
          $ref: "#/components/schemas/ArcanaNumeral"
    P5ArcanaResponse:
      type: object
      required:
        - ArcanaNumber
        - ArcanaName
        - ArcanaNumeral
      properties:
        ArcanaNumber:
          $ref: "#/components/schemas/ArcanaNumber"
        ArcanaName:
          $ref: "#/components/schemas/ArcanaName"
        ArcanaNumeral:
          $ref: "#/components/schemas/ArcanaNumeral"
    P5PersonaSkills:
      type: object
      properties:
        SkillName:
          $ref: "#/components/schemas/P5SkillName"
        SkillCost:
          $ref: "#/components/schemas/P5SkillCost"
        SkillEffect:
          $ref: "#/components/schemas/P5SkillEffect"
        CreatedAt:
          $ref: "#/components/schemas/CreatedAt"
        UpdatedAt:
          $ref: "#/components/schemas/UpdatedAt"
    P5PersonaSkillJunction:
      type: object
      properties:
        Name:
          $ref: "#/components/schemas/PersonaName"
        SkillName:
          $ref: "#/components/schemas/P5SkillName"
        SkillCost:
          $ref: "#/components/schemas/P5SkillCost"
        SkillEffect:
          $ref: "#/components/schemas/P5SkillEffect"
        LevelLearned:
          $ref: "#/components/schemas/P5SkillLevelLearned"
    ####################
    # Referenced Types #
    ####################
    # Generic Types
    CreatedAt:
      description: Represents when the object was added to the database.
      type: string
      x-go-type: time.Time
      x-oapi-codegen-extra-tags:
        json: "-"
    Level:
      description: The level of the Persona when first encountered; usually during fusion. The main character must be at least this level in order to fuse this Persona.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "minimum=1,maximum=99"
    UpdatedAt:
      description: Represents the last time when the object was updated in the database.
      type: string
      x-go-type: time.Time
      x-oapi-codegen-extra-tags:
        json: "-"
    # Arcanas
    ArcanaID:
      description: A universally unique identifier for identifying one of the 22 Major Arcana.
      type: string
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89abAB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}"
      x-oapi-codegen-extra-tags:
        gorm: "type:uuid;primaryKey"
    ArcanaName:
      description: The name of the Major Arcana.
      type: string
      x-oapi-codegen-extra-tags:
        validate: "minLength=3,maxLength=10"
    ArcanaNumber:
      description: A number from 0 - 21 representing one of the 22 Major Arcana from tarot cards.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "minimum=0,maximum=21"
    ArcanaNumeral:
      description: A Roman numeral representation of the Arcana Number. The exeception is the Fool Arcana which does not have an associated numeral. It is represented with "0".
      type: string
      x-oapi-codegen-extra-tags:
      validate: "minimum=1,maximum=5"
    # P5 Personas
    P5PersonaID:
      description: A universally unique identifier for identifying a Persona from Persona 5.
      type: string
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89abAB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}"
      x-oapi-codegen-extra-tags:
        gorm: "type:uuid;primaryKey"
    IsDLC:
      description: Represents if the Persona is only available via Downloadable Content.
      type: boolean
    IsTreasureDemon:
      description: Represents if the Persona is a treasure demon. Unique field to Persona 5 and Persona 5 Royal.
      type: boolean
    PersonaName:
      description: The name of the Persona.
      type: string
      x-oapi-codegen-extra-tags:
        validate: "minimum=1,maximum=24"
    # P5 Skills
    P5SkillName:
      description: The in-game name for the skill.
      type: string
    P5SkillCost:
      description: The cost to use the skill.
      type: string
    P5SkillEffect:
      description: The in-game description of what the skill does when used by the player.
      type: string
    P5SkillLevelLearned:
      description: The in-game level when the Persona learns the skill.
      type: integer
    # Stats
    Strength:
      description: An integer that represents the Persona's Strength stat.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "minimum=1,maximum=99"
    Magic:
      description: An integer that represents the Persona's Magic stat.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "minimum=1,maximum=99"
    Endurance:
      description: An integer that represents the Persona's Endurance stat.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "minimum=1,maximum=99"
    Agility:
      description: An integer that represents the Persona's Agility stat.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "minimum=1,maximum=99"
    Luck:
      description: An integer that represents the Persona's Luck stat.
      type: integer
      x-oapi-codegen-extra-tags:
        validate: "minimum=1,maximum=99"
